version: '4'
services:
  db:
    image: bitnami/mongodb:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: always
